version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      tennus_net:
        ipv4_address: 172.45.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  anaconda:
    build:
      context: ./nodo
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./notebooks:/notebooks
      - ./nodo:/nodo
    ports:
      - "8888:8888"
      - "80:80"
    depends_on:
      - mysql
      - mongodb
    networks:
      tennus_net:
        ipv4_address: 172.45.0.3

  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: tennus_data_analitica
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      tennus_net:
        ipv4_address: 172.45.0.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    networks:
      tennus_net:
        ipv4_address: 172.45.0.8
    depends_on:
      - mysql

networks:
  tennus_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.45.0.0/16

volumes:
  mysql_data:
  mongodb_data: